dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.4.0
  - OpenZeppelin/openzeppelin-contracts@4.4.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.0'  
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.0'
networks:
  default: development
  development:
    _subscriptionId: 1406
    _keyhash: '0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc'
    _callbackGasLimit: 100000
    _requestConfirmations: 3
    _numWords: 2
  rinkeby: 
    vrf_coordinator: '0x6168499c0cFfCaCD319c818142124B7A15E857ab'
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    link_token: '0x01BE23585060835E02B77ef475b0Cc51aA1e0709'
    _subscriptionId: 1406
    _keyhash: '0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc'
    _callbackGasLimit: 100000
    _requestConfirmations: 3
    _numWords: 2
    verify: true
  mainnet-fork:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False 
wallets:
  from_key: ${PRIVATE_KEY}        